---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./../base
namePrefix: local-

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: web-deployment
      namespace: netflix-clone
    spec:
      replicas: 2
      template:
        spec:
          containers:
            - name: web-server
              image: registry.dev.dramisinfo.com/netflix-clone/netflix-clone-web:latest
