apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: netflix-clone
  labels:
    app: sample-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-web
  template:
    metadata:
      labels:
        app: sample-web
    spec:
      containers:
        - name: web-server
          image: stefanprodan/podinfo
          ports:
            - containerPort: 9898
          resources:
            limits:
              cpu: 150m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 64Mi
