#create secrets for mongodb
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: netflix-clone
type: Opaque
stringData:
  password: admin123
---
apiVersion: opstreelabs.in/v1alpha1
kind: MongoDB
metadata:
  name: mongodb
  namespace: netflix-clone
spec:
  kubernetesConfig:
    image: "quay.io/opstree/mongo:v5.0.6"
    imagePullPolicy: IfNotPresent
    securityContext:
      fsGroup: 1001
  storage:
    accessModes:
      - ReadWriteOnce
    storageSize: 1Gi
    storageClass: local-path
  mongoDBSecurity:
    mongoDBAdminUser: admin
    secretRef:
      name: staging-mongodb-secret
      key: password
