name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build src --file src/Dockerfile --tag registry.dev.dramisinfo.com/netflix-clone/netflix-clone-web:${{ github.run_id }}
        
      -
        name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: registry.dev.dramisinfo.com/netflix-clone
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}
          
      - name: Push the Docker image to Harbor
        run: docker push registry.dev.dramisinfo.com/netflix-clone/netflix-clone-web:${{ github.run_id }}
