name: Docker Image CI

on:
  push:
    branches: ["main"]
    paths:
      - src/**
      - .github/**
  pull_request:
    branches: ["main"]
    paths:
      - src/**
      - .github/**

env:
  REGISTRY: registry.dev.dramisinfo.com/netflix-clone
  IMAGE_NAME: netflix-clone-web

jobs:
  checkout:
    name: Checkout code
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  # docker:
  #   name: Docker Build and Push
  #   runs-on: self-hosted
  #   steps:
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v3

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3

  #     - name: Log in to the Container registry
  #       uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
  #       with:
  #         registry: ${{ env.REGISTRY }}
  #         username: ${{ secrets.HARBOR_USERNAME }}
  #         password: ${{ secrets.HARBOR_PASSWORD }}

  #     - name: Build and push Docker image
  #       uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
  #       with:
  #         context: ./src
  #         push: ${{ github.event_name != 'pull_request' }}
  #         tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

  gitops:
    name: Update GitOps manifest
    runs-on: self-hosted
    needs: checkout
    steps:
      - name: Update docker tag
        run: |
          sed -i 's|image:.*|image: registry.dev.dramisinfo.com/netflix-clone/netflix-clone-web:31caa55a5873f619aa49f43f3a7d8ec3a2e4910f|' ./deploy/base/deployment.yaml
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add ./deploy/base/deployment.yaml
          git commit -m "Update docker tag"
          git push
