name: Docker Image CI

on:
  push:
    branches: ["main"]
    paths:
      - src/**
      - .github/**
  pull_request:
    branches: ["main"]
    paths:
      - src/**
      - .github/**

env:
  REGISTRY: registry.dev.dramisinfo.com/netflix-clone
  IMAGE_NAME: netflix-clone-web

jobs:
  docker:
    name: Docker Build and Push
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ./src
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  gitops:
    name: Update GitOps manifest
    runs-on: self-hosted
    needs: docker
    steps:
      - name: Prepare
        id: prep
        run: |
          VERSION=${GITHUB_SHA::8}
          echo BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') >> $GITHUB_OUTPUT
          echo VERSION=${VERSION} >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4

      - name: Update docker tag
        run: |
          sed -i 's|image:.*|image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}|' ./deploy/base/deployment.yaml
          cat ./deploy/base/deployment.yaml

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          add: "."
          message: "[ci skip] deploy from ${{ steps.prep.outputs.VERSION }}"
          signoff: true
